=== fia7tempos/webdev/webdev/WebContent/xml/xml03.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT cdList (cd*)>
<!ELEMENT cd (subject, (band | singer)+, price, song+)>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT band (#PCDATA)>
<!ELEMENT singer (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT song (#PCDATA)>

=== fia7tempos/webdev/webdev/WebContent/xml/xml03.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cdList SYSTEM "xml03.dtd">
<cdList>
	<cd>
		<subject>SNOWFLAKE</subject>
		<singer>GFriend</singer>
		<price>10000</price>
		<song>Intro</song>
		<song>시간을 달려서</song>
		<song>내 이름을 불러줘</song>
		<song>사랑별</song>
	</cd>
	<cd>
		<subject>응답하라 1988 OST Part 2</subject>
		<singer>이적</singer>
		<price>20000</price>
		<song>걱정말아요 그대</song>
	</cd>
	<cd>
		<subject>어깨</subject>
		<singer>소유</singer>
		<singer>권정렬</singer>
		<price>30000</price>
		<song>어깨</song>
	</cd>
</cdList>
